---
language: generic
dist: trusty
sudo: required
services:
  - docker
env:
  global:
  - secure: "mXrvb5nOdkiJVxrwZTkBz3+BKGaB0nOCltX8zDP90kYCe+wrm1z/JPvNbg5pEE2GlvWYhWdkaBaBYXs9VwGMFIC9clD9tcwJZ6lirSORl9TEidJtw4Y5h53uaud5XJr+zCP1FXFHVgs5kzuhMfrOipeiih5zgjr6EU5dJFQGCKACHTojTW6ybB7y88rrFY5W4Vw/luD6qBteDVc+6ahjcvbpRE0F+xUCCyst2oxmfKZd1f382DDvgQkq/wREUTSExOFYXr5z+odWeiJqjKmWcSLLrTvgE+gGKNAfCNPo2GGDjUmRdqLXZnEz4zyvKORwSYSlRZMKO42vEDFEHjQKQeHYSwtF+MpL82da7zC8VFA20x5UjRmNpo5iNflnKHo7YjUf+/Pq+sRd3NUeUL7sPCNAXF1eXL5i26yRy7EXlx5STY7yWenlv1P1tQaJ0U0DFPnfoUelf2U5mHgmG9XgPq+oBVH+G2ntMnlaaMiXvnhlp6aXIpn4jzTWCyqRdnD5sdfGTavW/G9PHzuNpcjBX659mEDUuzUT0DC/nE2lh4CNm5AKsCxBGCd2Qp7iQo/MQtEXuB1EGW6PPb4pTiQs7I2VEKOUB1GNyR+zx6WKmfYKUNCKsT2n+Pmq3P8Xa4At3OrF6WIbKcS2siE9AJCoN7XaCD+z/mP6tzAtZZDPlWc="
  - secure: "RuNz93EWW1id4cm2XwAGNO7k9i2OkgrlIGTCHOhDIbQuKvx5Y3Cws9PLl2TXrld/zcT0tGHLF2wl0rPwoM8YsjuYLfrLlYvtYPkEVFPMuJKWbLtyEAqLSStJYfH3PiRTJkUSa3abI5LTbDCDnxkBOJA10sT6eQwxA5lFvmwjyyT6uC/JEuhhNaQ5mkeTQGf76biZRXq0SyfliJGyjckhZrIBBxhgYFocgMFuPSz5qeyG7XZx1+fiVMyfSjFV/yvGxxTBReqdr7EP3xFB9ojAa2pYwxtzDn/tL6339LmrOQWUsgnW/8ASBHXRz69rrrcHumlg7Abvrzi8BIwKh2G4+MXtPFLML2/kWoLLQ3kPcAbnauBNFJyVPFrkiEEnXcZWq3+Jl4jVrPu6FXTVy3/K2JoPYeXa2FOWRRHynDE142c6ZnUCb8Xy31jTZSNx6mnatdB52yFmlrFZjNmFTmqkbNHpmAJR8/JyuyjQucq6Vk8qAQE5lI3Hrl+u0qxWVvxbL4TJBnisSnNcBiQvUYlVb2eb4pRRZmfO/646xnmO6ugXh1cN40IspJkieug2YzdV1DWJBrttc1dkiJZ55lC8pRoUb/XdtR9qZjoqGXZQMq2uxd2a04zEu+3+xad5YDjho83xednHamKq4xZKmxVPII/xoxsjTWxKgoNAhUFMoS8="

before_install:
- docker --version

install:
- curl -L https://goss.rocks/install | sudo sh
- sudo pip install awscli

script:
- /bin/bash docker/label_containers.sh &&
  docker build -t smartz-wiki --file docker/Dockerfile . &&
  /bin/bash ./test/docker.sh &&
  docker images &&
  /bin/bash ./docker/upload_to_registry.sh smartz-wiki &&
  aws ecs --region eu-central-1 update-service --cluster smartz --service smartz-wiki --force-new-deployment

notifications:
  email:
    on_success: change
    on_failure: always
