---
language: generic
dist: trusty
sudo: required
services:
  - docker
env:
  global:
  - secure: "mXrvb5nOdkiJVxrwZTkBz3+BKGaB0nOCltX8zDP90kYCe+wrm1z/JPvNbg5pEE2GlvWYhWdkaBaBYXs9VwGMFIC9clD9tcwJZ6lirSORl9TEidJtw4Y5h53uaud5XJr+zCP1FXFHVgs5kzuhMfrOipeiih5zgjr6EU5dJFQGCKACHTojTW6ybB7y88rrFY5W4Vw/luD6qBteDVc+6ahjcvbpRE0F+xUCCyst2oxmfKZd1f382DDvgQkq/wREUTSExOFYXr5z+odWeiJqjKmWcSLLrTvgE+gGKNAfCNPo2GGDjUmRdqLXZnEz4zyvKORwSYSlRZMKO42vEDFEHjQKQeHYSwtF+MpL82da7zC8VFA20x5UjRmNpo5iNflnKHo7YjUf+/Pq+sRd3NUeUL7sPCNAXF1eXL5i26yRy7EXlx5STY7yWenlv1P1tQaJ0U0DFPnfoUelf2U5mHgmG9XgPq+oBVH+G2ntMnlaaMiXvnhlp6aXIpn4jzTWCyqRdnD5sdfGTavW/G9PHzuNpcjBX659mEDUuzUT0DC/nE2lh4CNm5AKsCxBGCd2Qp7iQo/MQtEXuB1EGW6PPb4pTiQs7I2VEKOUB1GNyR+zx6WKmfYKUNCKsT2n+Pmq3P8Xa4At3OrF6WIbKcS2siE9AJCoN7XaCD+z/mP6tzAtZZDPlWc="
  - secure: "xf6SkVeIdM579p+2IJkiOd5CEgIrZFZTYnBindMysG2a06gVb01pvvMsnUT6G4Oz/35uqAdmjeT5MLxKM7IqX4/Ec7HFxjl+wuVqSqM3PxzB6mrlmZUaPqxE+PmTGjnGguQt2X7fJuCCF5nllN1RboGlyk9jtDSaJe5lmmHTz5fo/tormhFVT267ixUXSQUDd5e6aHS/+sthaxeX4Jk8bhCHwucHMb2ekOGHPEVKarmyATofwjhAWNeeFOYh7xn/EhF+7BiaHezNZxyaqXC4Scbo1/B0DL9VF89ZI1XUJgzA7YG6WHyVj8dE318XW2Gw4cJLGOZQSM5hziyLDGDbFBXSfecRXCvc/DOdXxXrjD+3j9Z9HmDv/1heNClY48wL6tEMPlWC/STVtrFygfVO1GcBqRXuTFQKRXHsbLxYoABtvlpOG4v089zWOr1Wn4JuzgF1tuPo0yIkCn2Hqb238EJvgFOKknpN7Wvb0217yT/ZuO3IMdrwi32wX4AIdc/X/6+LZhtZwg+6d+VVlvKok9/39//MAe/siQfdH9vO66abAK6jULtbiJ40z3cPjYSW2aC0ki18Upb7cmD9J+dxgWgm62h1WYHvkiDoGWFgkd3aHVz5y7kycOQ0/jkfXlKmvjZTrjEqHUpxQosPVsgak7CIFeTZDUDlh985XF412xs="

before_install:
- docker --version

install:
- curl -L https://goss.rocks/install | sudo sh
- sudo pip install awscli==1.16.36

script:
- /bin/bash docker/label_containers.sh &&
  docker build -t smartz-wiki --file docker/Dockerfile . &&
  /bin/bash ./test/docker.sh &&
  docker images &&
  /bin/bash ./docker/upload_to_registry.sh smartz-wiki &&
  aws ecs --region eu-central-1 update-service --cluster smartz --service smartz-wiki --force-new-deployment

notifications:
  email:
    on_success: change
    on_failure: always
